### ISSUE TITLE
Need a way to stop commands

### ISSUE THREAD

**Issue by sebgeiser** [formulahendry/vscode-terminal#2]
Hello, Very nice tool.

I just need a way to stop or (kill) commands launched with it.
This to prevent commands to execute forever and in some case to fill the terminal output.

Thanks

**Comment by formulahendry** [comment]
@sebgeiser Thanks for the feedback! I have added support to stop the running commands. Please install the [latest version](https://marketplace.visualstudio.com/items?itemName=formulahendry.terminal) to have a look. To stop the running commands, use shortcut `Ctrl+Alt+C`, or press `F1` and then select/type `Stop Terminal Command`

**Comment by sebgeiser** [comment]
Great

Thanks a lot.

**Comment by faceyspacey** [comment]
This isn't working for me on mac. control + option/alt + C isn't stopping long running commands. 
Any suggestion?

**Comment by formulahendry** [comment]
@faceyspacey Are you using `Ctrl+Alt+R` to trigger? Actually, VSCode itself has the Integrated Terminal.

**Comment by faceyspacey** [comment]
When I do that, it opens the "OUTPUT" tab. I open the terminal by a custom keyboard shortcut. 

Here's a screenshot:

![screen shot 2017-07-08 at 7 43 03 pm](https://user-images.githubusercontent.com/154732/27990741-b0986dfa-6415-11e7-8f9d-af450f24f829.png)


I pasted it because I just read in your readme that VS Code has its own terminal. I've been using yours for the longest time though--or so I thought. Is your terminal in the output tab? My output tab is full of errors and isn't working when I do `CTRL+ALT+R`.

**Comment by formulahendry** [comment]
Yes, my terminal is in the output tab. And you are trying to run a `package.json` file, so you will see that output. And the run is already done, you really did not need to stop it.

**Comment by faceyspacey** [comment]
Oh my bad, all this time I thought the integrated terminal was your terminal. I added your package long ago--i guess before VS Code added it, and only started using it once it appeared lol. Sorry about this.
