### ISSUE TITLE
output characters display incorrectly if OS is Simplified Chinese version

### ISSUE THREAD

**Issue by CNMan** [formulahendry/vscode-terminal#3]
![2016-07-09_151831](https://cloud.githubusercontent.com/assets/8692234/16706688/7112cd34-45e8-11e6-9ca7-aa634e859212.png)

**Comment by formulahendry** [comment]
@CNMan Which OS are you using?

**Comment by CNMan** [comment]
windows server 2012 r2
windows server 2016 tp5

**Comment by formulahendry** [comment]
Hi @CNMan , thanks for your info. I could repro this issue but I would hold on the bug fix or feature development for now because:

1. VS Code already has great built-in support for the terminal. And it just miss one feature of this extension: ability to run the entire text of current active text editor. I have already sent the [Pull request](https://github.com/Microsoft/vscode/pull/9480) and hope it could be merged. If it has been merged, I think this extension could be retired. :smile: 
2. I have another extension: [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner). And it is superset of the Terminal extension since it not only supports `powershell, bat/cmd, bash/sh` but also supports other script language like `js, php, python, perl, ruby, go, lua, groovy` even `F#, C#`.

Therefore, I suggest you to use [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner). The issue should not exist in this extension. Look forward to your feedback!

**Comment by CNMan** [comment]
![2016-07-23_164500](https://cloud.githubusercontent.com/assets/8692234/17077048/de8e5948-50f4-11e6-999f-df22d4041417.png)
uninstall Terminal and install Code Runner,but has same issue.

**Comment by formulahendry** [comment]
Could you let me know your locale setting?
![image](https://cloud.githubusercontent.com/assets/1050213/17079038/f770fcd0-5136-11e6-976c-b473d9ee2148.png)

**Comment by CNMan** [comment]
![2016-07-24_022118](https://cloud.githubusercontent.com/assets/8692234/17079521/5c5d28fe-5145-11e6-9aa0-5aa8a18b8b10.png)

**Comment by formulahendry** [comment]
Hi @CNMan , I found a workaround for this issue (though make the output be English instead of Chinese). Anyway, it eliminates the messy code. The workaround is to update the config for bat of code-runner.executorMap
```json
{
    "code-runner.executorMap": {
        "bat": "chcp 65001 |"
    }
}
```
Refer to [stackoverflow](http://stackoverflow.com/a/15470145), [#2190](https://github.com/nodejs/node-v0.x-archive/issues/2190) and [#2196](https://github.com/nodejs/node-v0.x-archive/issues/2196)

**Comment by formulahendry** [comment]
Hi @CNMan , as another option, you could use Code Runner to run it in built-in terminal:
``` json
{
    "code-runner.runInTerminal": true
}
```
