### ISSUE TITLE
Is there a way to run a .bashrc file or similar on startup?

### ISSUE THREAD

**Issue by MattMcFarland** [formulahendry/vscode-terminal#4]
Hi, great extension!!! 

Just as I put in the subject, is there any way that we can configure this extension to run a .bashrc file when a new terminal instance is created?

**Comment by formulahendry** [comment]
Hi @MattMcFarland , sorry I am not quite familiar with the .bashrc file. After some investigation, maybe you could try this extension: [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) (It is superset of the Terminal extension since it not only supports `powershell, bat/cmd, bash/sh` but also supports other script language like `js, php, python, perl, ruby, go, lua, groovy` even `F#, C#`). Moreover, unlike this Terminal extension to run command directly of each line one by one, It would called shellscript (bash/sh) with `bash` command. You may also override the code-runner.executorMap to specify the bashrc file like below. But I am not sure whether it will work since the current way to run script is non-interactive. Or maybe `bash --login` to execute `/etc/profile`?
```json
{
    "code-runner.executorMap": {
        "shellscript": "bash --rcfile path/to/rcfile"
    }
}
```

**Comment by MattMcFarland** [comment]
Thanks for the reply!  The .bashrc file just sets up the terminal environment when you start it.  It is commonly used to set the prompt and environment variables.  Do you know if there is an easy way to execute a command at start?  "source .bashrc"  - or something?  I think that would be a nice addition to mac / linux users.

**Comment by formulahendry** [comment]
Hi @MattMcFarland , sorry currently this Terminal extension does not support this function but there are two other alternatives for your requirement:

- Option#1: As I mentioned, you could use [Code Runner extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner), it supports customization on startup.
  - After installing the extension, you could set the config like below, then run any shell script you want before running the selected shell script:
  ```json
  {
    "code-runner.executorMap": {
        "shellscript": "echo before run; bash"
    }
  }
  ```
  - Or, set the config like below to run `/etc/profile` and `~/profile` before running the selected shell script, (refer to this [artilce](http://stefaanlippens.net/bashrc_and_others) ):
  ```json
  {
    "code-runner.executorMap": {
        "shellscript": "bash --login"
    }
  }
  ```
- Option#2: Use built-in Terminal of VS Code. VS Code already has basic built-in support for the terminal from v1.2 and add 'run selected text' in v1.3. For now, it just miss one feature of this extension: ability to run the entire text of current active text editor. I have already sent the [Pull request](https://github.com/Microsoft/vscode/pull/9480) and hope it could be merged. If it has been merged, I think this extension could be retired. :smile: Thus, I just hold on the bug fix or feature development for this extension for now and put more effort on [Code Runner extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)

**Comment by danlafreniere** [comment]
I know this was closed but I wanted to comment in case my solution helps anyone else. I did a work-around where I forced the integrated terminal to run as a login shell (sources bash_profile) and then within bash_profile I source bashrc.

First within your VSCode user settings file add:
```
"terminal.integrated.shellArgs.osx": [ "-l" ]
```
which will force the login shell to run. 

Then add this to your .bash_profile file in root: 
```
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
```

This serves to basically give us the same config for login and non-login shells. See: http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
