### ISSUE TITLE
Move current directory to that of the open file

### ISSUE THREAD

**Issue by pwmcintyre** [formulahendry/vscode-terminal#6]
Let's say i'm working on a project in Code and I have a folder open.
Then I have a run.sh file open hit the 'run' command.
I'd assume a command like 'pwd' in unix or 'dir' in Windows to return that folder

At the moment 'pwd' returns / so trying to do a 'mkdir temp' fails with permissions issues

**Comment by formulahendry** [comment]
Hi @pwmcintyre , sorry the support for this scenario is limited in this extension, but you could try this extension: [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner). You could set working directory in config, otherwise it use the path of root folder open in VS Code. Also, you could use `cd %~dp0` to change the directory. Moreover, this extension's function has merged into [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) and more support will be applied in Code Runner. If you have more requests, you could submit request in [Code Runner extension repo](https://github.com/formulahendry/vscode-code-runner/issues) :smiley:
